### PR TITLE
Make enchant_get_user_language public

### PR DESCRIPTION
**Pull request by rrthomas**
Also remove editor settings comments

### CODE REVIEW

**Comment by TingPing** [comment]
btw `g_strdup` is guaranteed to use system malloc since 2.46 I believe.

**Comment by rrthomas** [comment]
Thanks @TingPing; could you confirm this with a documentation or source code reference, please? We can't assume 2.46 for a few years, but it could be one of those problems that ends up solving itself by waiting, so it would be good to document it.

**Comment by TingPing** [comment]
https://github.com/GNOME/glib/commit/3be6ed60aa58095691bd697344765e715a327fc1 is the commit that removed custom allocator support.

**Comment by rrthomas** [comment]
Thanks; I ought to have remembered this, as I filed a bug asking for custom allocator support to be fixed that was eventually closed when it was removed!

**Pull request merged**
