### PR TITLE
Remove Windows-specific prefix finding code, and obsolete OpenOffice dictionary finder

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by TingPing** [comment]
As mentioned you do need to use `g_win32_get_package_installation_directory_of_module()` *somewhere*. (That is effectively the same code as this).

**Comment by rrthomas** [comment]
Thanks as ever, @TingPing. Please can you clarify: 1) where was it mentioned, and 2) why is it needed? Also, thanks for the pointer to the glib API.

**Comment by TingPing** [comment]
Mentioned it here: https://github.com/AbiWord/enchant/issues/51#issuecomment-273936170

The reason you need these things on Windows/OSX/Snap is because they are pulled out of their prefix into a portable location. So in msys2 it works ootb but when an installer is made that shoves it into program files it needs to dynamically find the correct root (which that function does).

**Comment by rrthomas** [comment]
Thanks for the explanation, @TingPing. I am keeping this in mind, but now I will add an issue for this; I plan to make this work in a platform-independent way. (If this turns out not to be possible, then some neater packaging of the previous code is of course an option.)

**Comment by TingPing** [comment]
You basically need a windows path for it but OSX and Snap can easily be accomplished by supporting an env var to set the prefix.

**Comment by rrthomas** [comment]
@TingPing, thanks; could you please comment on the new issue #86? In particular, if it's not possible with an env var on Windows, why not?

**Pull request merged**
