### PR TITLE
Minor fixes and new release 2.2.5.

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by lantw44** [comment]
We just found that the release tarball `enchant-2.2.5.tar.gz` was modified. It is known to cause [JHBuild to fail because of mismatching checksums](https://gitlab.gnome.org/GNOME/jhbuild/merge_requests/27), and it was also found that [Fedora rawhide recorded the old hash in its `sources` file](https://src.fedoraproject.org/rpms/enchant2/blob/7fa5ab63894ad1cb1830aa1615dee0c6fbe0ec2d/f/sources).
```
$ sha256 old/enchant-2.2.5.tar.gz new/enchant-2.2.5.tar.gz 
SHA256 (old/enchant-2.2.5.tar.gz) = ffce4ea00dbda1478d91c3e1538cadfe5761d9d6c0ceb27bc3dba51882fe1c47
SHA256 (new/enchant-2.2.5.tar.gz) = ee8a663295c0e039b05d418af065ebcba9e539f785531e552e908030bec48164
```
```
$ sha512 old/enchant-2.2.5.tar.gz new/enchant-2.2.5.tar.gz 
SHA512 (old/enchant-2.2.5.tar.gz) = cc4d00ea2c94fcf2cef0281e13b86c49cfbff74c60315126bab8b1d91d8da1fb8fd0dc215a1eb44b07d8be33bc54cb9e63107874ef1caa04714fbe4b7484280f
SHA512 (new/enchant-2.2.5.tar.gz) = 6d83462eb4dbb594599bcb328d28695ee9c5d7240143d86a8fecf9504989209439fec4063c2e3d8360dac63546063cfbfd54fe603fe3041df382e0582be078d3
```
Why the released file was modified? Shouldn't the modification be done by making a new release?

**Comment by rrthomas** [comment]
I can only offer my humble apologies, it seems I've made the same release twice.

**Comment by csaavedra** [comment]
May I suggest you make a new release with a bumped version number? That will prevent further mismatching issues when systems try to work with the latest release. You can just call it 2.2.5.1 too.

**Comment by rrthomas** [comment]
I'll do that later today; thanks very much for the heads up and suggestion.

**Comment by lantw44** [comment]
I saw you made a new release. Are you going to rollback the release tarball of 2.2.5 to the original version?

**Comment by rrthomas** [comment]
I wasn't planning to. At this stage, I'm not sure that would help much: git history records two 2.2.5 releases, I would have to re-delete and re-tag 2.2.5, and I'm not sure that the build is reproducible in any case (and I don't have the original tarball). Probably best just to move on!

**Comment by lantw44** [comment]
The original tarball is still available on https://src.fedoraproject.org/repo/pkgs/enchant2/enchant-2.2.5.tar.gz/.

**Comment by rrthomas** [comment]
Thanks, but I'd rather not publish something I haven't generated. What's the problem you're trying to solve here?

**Comment by lantw44** [comment]
I think it is fine to keep the current 2.2.5 release. I just thought it may be better to rollback to the original version if it can be assumed distribitions haven't picked up the new 2.2.5 release, so users who try to rebuild the package locally are less likely to be confused by the issue.

**Comment by rrthomas** [comment]
Ok! I think it's safe to assume that packagers will move to the latest release.

**Pull request merged**
