### PR TITLE
Update nuspell in CI

### PR DESCRIPTION
**Pull request by dimztimz**
Updates nuspell in CI. Instead of the ppa, Nuspell is built and installed from source since the ppa is not updated and I don't plan on updating it.

### CODE REVIEW

**Comment by rrthomas** [comment]
Is the nuspell PPA no longer being updated? It is still documented on the Wiki: https://github.com/nuspell/nuspell/wiki/Nuspell-packaged-binaries

**Comment by dimztimz** [comment]
It won't be updated anymore. Instead the official Ubuntu repositories should be used since 21.04. For CI you'll probably need to wait for 22.04 (the next LTS version).

**Comment by rrthomas** [comment]
Thanks for explaining; it would be good to announce this on the blog, and remove it from the Wiki installation page. Meanwhile, this PR looks good, thanks. I just need to land my PR to fix CI on Ubuntu first.

**Comment by rrthomas** [comment]
@dimztimz Please could you rebase this PR now I've made my changes to fix CI on Ubuntu?

**Comment by dimztimz** [comment]
> @dimztimz Please could you rebase this PR now I've made my changes to fix CI on Ubuntu?

Done. Seems to work.

**Pull request merged**
