### PR TITLE
Migrate CI to Github Actions

### PR DESCRIPTION
**Pull request by dimztimz**
This patch migrates the CI to Github Actions. Github Actions is much faster than Appveyor.

### CODE REVIEW

**Comment by rrthomas** [comment]
This is looking awesome; it would be *fantastic* if we could have all platforms on one CI system (this was a good thing when Travis stopped being free, but I was able to move everything to AppVeyor).

**Comment by dimztimz** [comment]
This is done.

**Comment by rrthomas** [comment]
You're a total star @dimztimz, thanks so much!

**Comment by dimztimz** [comment]
To completely remove AppVeyor you need to remove the webhook in the repository settings. Or maybe it should be uninstalled from the list of Github Apps. It seems like there are still remnants of it in the other pull request i just sent.

**Comment by rrthomas** [comment]
Thanks for the hint; I don't have the ability to remove it but I'll ask.

**Comment by rrthomas** [comment]
Done!

**Pull request merged**
