### PR TITLE
added Doxygen documentation generation

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Review by rrthomas — COMMENTED** [review]
Is it necessary to have the `Doxyfile`, and if so, would it be possible to have a much shorter file containing just the settings needed for this project?

**Comment by rrthomas** [comment]
Thanks for this, looks like a useful addition.

**Comment by PanderMusubi** [comment]
Doxygen generates a file and make changes to it. To keep it in this long version, it is easy to diff what the customizations are, also for upgrading to a newer version Doxygen. This is how most people use it, I haven't seen shorter versions being used so far.

What you could do, is publish the API documentation with each release on https://abiword.github.io/enchant/ For Nuspell we do that on https://nuspell.github.io/ via the link API Docs. Note that it doesn't link to the main index.html but a more directly useful page. We use the following helper script to do this https://github.com/nuspell/nuspell.github.io/blob/master/update-api-doc.sh

**Comment by rrthomas** [comment]
OK, thanks for the explanation!

**Pull request merged**
