### PR TITLE
Fixes from Fedora package

### PR DESCRIPTION
**Pull request by manisandro**
Hi

These are two fixes I needed to apply for the Fedora package.

### CODE REVIEW

**Comment by rrthomas** [comment]
Thanks for these fixes. Indeed I don't test out-of-tree Vala builds (I guess you're building direct from Vala?). I probably should do that.

I think it's simpler just to use `$(srcdir)` as the `--vapidir` setting.

As to the cast, I don't understand that, as the return value of `Intl.get_language_names` is precisely `unowned string[]`. I'll file an issue with the Vala project.

Hence, I'll close this PR, but thanks very much for bringing these problems to my attention, and for packaging Enchant.

**Comment by rrthomas** [comment]
(I will of course make a  new release when I've fixed the issues.)

**Comment by rrthomas** [comment]
Also: the cast you suggest does not fix the C compiler warning for me.

**Comment by manisandro** [comment]
> I guess you're building direct from Vala?

Not really, I build a native and a mingw package from the same source tree, so i.e.
```
mkdir build_native
pushd build_native
../configure
# etc
```

**Comment by rrthomas** [comment]
Thanks for getting back to me! I don't understand why you needed the `--vapidir` setting fixed, as you weren't running the Vala compiler.

**Comment by rrthomas** [comment]
It turns out that a workaround that disables the Clang warnings and downgrades the GCC error to a warning is included in Vala 0.56.15, so I just have to rebuild with a later Vala (I was using 0.56.0). I will do this shortly and make a new release. It would still be good to know what went wrong for you without the `--vapidir` setting fixed.

**Comment by rrthomas** [comment]
I have opened an issue about the Vala problem, which should be fixed by the above-mentioned workaround, but seems to be a different variant from those previously encountered: https://gitlab.gnome.org/GNOME/vala/-/issues/1546

**Pull request closed without merging**
