### PR TITLE
Reduce dependency on some Gnulib modules

### PR DESCRIPTION
**Pull request by dimztimz**

### CODE REVIEW

**Comment by rrthomas** [comment]
I like the use of GLib macros. I don't like the removal of `strchrnul`, this just makes the code worse IMO. The manual copy of `gnu-make` is not a good idea while gnulib is still used, but it's good to know that it can be done—maybe it would be a good idea to have a list of the remaining modules that *could* be trivially removed.

**Comment by dimztimz** [comment]
None of the current gnulib modules are trivial to remove but these 3 stuff were the easier ones. If at some point alternative build system should be considered then gnulib can not stay, piece by piece it should be removed.

Regardung strchrnul its just a matter of taste. Very few lines of code are affected. This new code is even faster because one call to strchrnul is completely removed. It is pointless to use strchr[nul] when later you are going to iterate char by char.

Giving a second thought, the whole functions can be refactored to use for loop and no strchr.

**Comment by rrthomas** [comment]
Of course if the code currently using `strchrnul` can be simplified to not need it, that's great!

**Comment by dimztimz** [comment]
Sorry but im not going to change this anymore. Obviosly you like gnulib and posix too much.

**Comment by rrthomas** [comment]
Thanks for trying!

**Pull request closed without merging**
